### PR TITLE
move endeavour to suit a new explanation and add fedora for #173

### PR DESCRIPTION
**Pull request by PipeItToDevNull**

### CODE REVIEW

**Comment by PipeItToDevNull** [comment]
If no one has any qualms, this is a simple merge

**Comment by abUwUser** [comment]
i don't have any major complains, it looks fine, altough fedora doesn't seem that marketed well on the phrase. may we mention that it aims to provide the most clean and well integrated gnome experience? or something like that?

**Comment by PipeItToDevNull** [comment]
> i don't have any major complains, it looks fine, altough fedora doesn't seem that marketed well on the phrase. may we mention that it aims to provide the most clean and well integrated gnome experience? or something like that?

No one reading our article knows what Gnome is, our Article on Mint does not call out Cinnamon for I assume the same reason

**Comment by abUwUser** [comment]
understandable. also i have another concern with "workstation OS", because ppl will think it is an OS for enterprises, or at least thats what i think when i hear "workstation"

**Comment by abUwUser** [comment]
may you link the PR and the issue with a keyword so that it could be closed automatically? check https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
